# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515505b96e5e05629ba3742d7a9710e4c60581706655ca1373e639dbdfa66810cc04b5f70cb2b6ae5fc87f8a8f435f8cb128466d73bb33d1e42ec2971c280eb4

test:
  secret_key_base: dc7d87571c2dff64e617e6d27cbe57525f9aa0fa84a57900df0603780782f1ca85f5f26d445f5fd33bf3d2813ead33e325124ad966aa7852eca296172e3eeb07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
